version: "3.7"

services:
  fluent-bit:
    image: docker.shiyou.kingsoft.com/mirror/fluent/fluent-bit:1.8.9
    container_name: fluent-bit-producer
    network_mode: host
    depends_on:
      - cmak
    volumes:
      - ./config/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./data/fluent-bit:/fluent-bit/tmp
  cmak:
    image: docker.shiyou.kingsoft.com/mirror/hlebalbau/kafka-manager:3.0.0.5
    container_name: cmak
    network_mode: host
    depends_on:
      - kafka
    # ports:
    #   - "9000:9000"
    environment:
      ZK_HOSTS: localhost:2181
  kafka:
    image: docker.shiyou.kingsoft.com/mirror/confluentinc/cp-kafka:7.0.0
    container_name: kafka
    network_mode: host
    depends_on:
      - zookeeper
    # ports:
    #   - "9092:9092"
    #   - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'localhost:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  zookeeper:
    image: docker.shiyou.kingsoft.com/mirror/zookeeper:3.7.0
    hostname: zookeeper
    container_name: zookeeper
    network_mode: host
    # ports:
    #   - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
