high-availability.jobmanager.port: 6123
blob.server.port: 6124
rest.bind-port: 8081
# rest.bind-address: "0.0.0.0"
query.server.port: 6125

jobmanager.memory.process.size: 1600m

high-availability: zookeeper
high-availability.zookeeper.quorum: localhost:2181
high-availability.zookeeper.path.root: /flink
high-availability.cluster-id: /cluster_one
high-availability.storageDir: s3a://seayoo-dev-analytics/flink/ha
zookeeper.sasl.disable: true

state.backend: rocksdb
state.checkpoints.dir: s3a://seayoo-dev-analytics/flink/checkpoints
state.checkpoint-storage: filesystem
state.savepoints.dir: s3a://seayoo-dev-analytics/flink/savepoints
execution.checkpointing.interval: 60000
state.checkpoints.num-retained: 10

s3.endpoint: s3.cn-northwest-1.amazonaws.com.cn
fs.s3a.aws.credentials.provider: org.apache.hadoop.fs.s3a.auth.AssumedRoleCredentialProvider
fs.s3a.assumed.role.credentials.provider: com.amazonaws.auth.InstanceProfileCredentialsProvider
fs.s3a.assumed.role.arn: arn:aws:iam::121828301502:role/shiyou-labs/service/flink-20220210080848245200000001

fs.allowed-fallback-filesystems: s3

# 以下信息为 Flink 自动添加，可以删除
